
import { CookingPot } from "lucide-react";
import Image from "next/image";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cooking Techniques',
  description: 'Our guides cover techniques from sauté to sous-vide. Learn everything you need to know to start cooking like a professional in your own kitchen.',
};

const techniques = [
  { name: "Sautéing", image: "https://images.unsplash.com/photo-1583337731735-344413475451?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "saute pan", description: "Quickly cooking food in a small amount of fat over relatively high heat. It's perfect for browning ingredients and developing complex flavors." },
  { name: "Roasting", image: "https://images.unsplash.com/photo-1588694883132-85012e8b15e4?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "roasting vegetables", description: "Cooking food with dry heat in an oven, a method that creates a browned, flavorful exterior and a moist, tender interior. Ideal for meats and vegetables." },
  { name: "Braising", image: "https://images.unsplash.com/photo-1631292782168-a35985b93d79?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "braised meat", description: "A combination-cooking method that uses both wet and dry heats. Food is first seared at a high temperature, then finished in a covered pot with liquid." },
  { name: "Grilling", image: "https://images.unsplash.com/photo-1628268907923-34861a521469?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "food grilling", description: "Cooking food over direct, radiant heat on a grill. This technique imparts a smoky flavor and characteristic sear marks, perfect for summer barbecues." },
  { name: "Steaming", image: "https://images.unsplash.com/photo-1604537466507-910d6d5165a2?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "steamed vegetables", description: "Cooking with moist heat generated by boiling water. This gentle method helps retain nutrients, moisture, and the natural color of the food, especially vegetables." },
  { name: "Poaching", image: "https://images.unsplash.com/photo-1631292782168-a35985b93d79?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "poached egg", description: "Gently cooking food in a liquid, such as water, milk, stock, or wine. It's ideal for delicate items like eggs, fish, and fruit." },
  { name: "Blanching", image: "https://images.unsplash.com/photo-1558985250-29a4a751654a?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "blanching vegetables", description: "Scalding vegetables in boiling water or steam for a short time, then plunging them into ice water to stop the cooking process. It sets color and softens food." },
  { name: "Sous-Vide", image: "https://images.unsplash.com/photo-1604537466507-910d6d5165a2?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "sous vide machine", description: "Cooking food in a vacuum-sealed bag in a precisely temperature-controlled water bath. This method ensures perfect, even cooking every time." },
  { name: "Stir-Frying", image: "https://images.unsplash.com/photo-1549618112-25801f9f5926?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "stir fry wok", description: "A Chinese cooking technique where ingredients are fried in a small amount of very hot oil while being stirred or tossed in a wok. It's fast and fresh." },
  { name: "Baking", image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "baking cake", description: "Cooking food with prolonged dry heat, normally in an oven. Most commonly used for preparing bread, cakes, pastries, and pies." },
  { name: "Frying", image: "https://images.unsplash.com/photo-1639587489502-867355153545?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "deep frying", description: "Cooking food in hot fat or oil, typically in a shallow pan (pan-frying) or deep vessel (deep-frying). This method creates a crispy, golden-brown crust." },
  { name: "Fermenting", image: "https://images.unsplash.com/photo-1594313223274-4264665cf1d2?q=80&w=400&h=300&auto=format&fit=crop", dataAiHint: "fermenting jars", description: "A metabolic process that produces chemical changes in organic substrates through the action of enzymes. In food, it creates complex flavors in items like kimchi, sourdough, and yogurt." }
];

export default function TechniquesPage() {
  return (
    <div className="container px-4 py-12 md:py-24">
      <div className="mx-auto flex max-w-3xl flex-col items-center text-center mb-12">
        <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary/10">
          <CookingPot className="h-8 w-8 text-primary" />
        </div>
        <h1 className="font-headline text-4xl font-bold md:text-5xl">
          Master Your Kitchen
        </h1>
        <p className="mt-4 text-lg text-muted-foreground">
          Dive into our comprehensive guides on cooking techniques. From the essential sauté to advanced sous-vide, we cover everything you need to know to cook like a professional. Mastering culinary techniques is the key to unlocking your full potential in the kitchen. It's not just about following recipes; it's about understanding the 'why' behind the 'how'. Our detailed guides break down fundamental and advanced methods into easy-to-understand steps. Learn how to properly sear a steak to achieve a perfect crust, or how to emulsify a vinaigrette that won't separate. We explore the science behind cooking, explaining how heat, fat, and acid interact to transform ingredients and create flavor. Each technique guide includes information on the best equipment to use, common mistakes to avoid, and pro tips to elevate your results. Whether you want to perfect your knife skills for faster prep, learn the art of bread making, or explore the world of molecular gastronomy, our resources are here to support you. By building a strong foundation of techniques, you'll gain the confidence to experiment, create your own recipes, and truly express yourself through food.
        </p>
      </div>
       <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
        {techniques.map((technique) => (
          <Card key={technique.name} className="overflow-hidden flex flex-col group transition-all duration-300 hover:shadow-xl hover:-translate-y-1">
            <CardHeader className="p-0">
              <div className="aspect-video relative overflow-hidden">
                <Image
                  src={technique.image}
                  alt={technique.name}
                  fill
                  className="object-cover group-hover:scale-105 transition-transform duration-300"
                  data-ai-hint={technique.dataAiHint}
                />
              </div>
            </CardHeader>
            <CardContent className="p-6 flex-grow">
              <h2 className="font-headline text-xl leading-snug mb-2">
                {technique.name}
              </h2>
              <p className="text-muted-foreground text-sm">{technique.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
